// src/assets/rankingIcons.ts

// O tipo que o componente Image do React Native espera.
type ImageSource = number; 

// Um mapa onde a chave é o nome do ranking e o valor é um array de imagens.
type RankingMap = Record<string, ImageSource[]>;

export const rankingIcons: RankingMap = {
  
  Wood: [
    require("./Wood/shield-wood-1.png"),
    require("./Wood/shield-wood-2.png"),
    require("./Wood/shield-wood-3.png"),
    require("./Wood/shield-wood-4.png"),
    require("./Wood/shield-wood-5.png"),
    require("./Wood/shield-wood-6.png"),
    require("./Wood/shield-wood-7.png"),
    require("./Wood/shield-wood-8.png"),
    require("./Wood/shield-wood-9.png"),
    require("./Wood/shield-wood-10.png"),
    require("./Wood/shield-wood-11.png"),
    require("./Wood/shield-wood-12.png"),
  ],
  Bronze: [
    require("./Bronze/shield-bronze-1.png"), 
    require("./Bronze/shield-bronze-2.png"),
    require("./Bronze/shield-bronze-3.png"),
    require("./Bronze/shield-bronze-4.png"),
    require("./Bronze/shield-bronze-5.png"),
    require("./Bronze/shield-bronze-6.png"),
    require("./Bronze/shield-bronze-7.png"),
    require("./Bronze/shield-bronze-8.png"),
    require("./Bronze/shield-bronze-9.png"),
    require("./Bronze/shield-bronze-10.png"),
    require("./Bronze/shield-bronze-11.png"),
    require("./Bronze/shield-bronze-12.png"),
  ],
  Silver: [
    require("./Silver/shield-silver-1.png"),
    require("./Silver/shield-silver-2.png"),
    require("./Silver/shield-silver-3.png"),
    require("./Silver/shield-silver-4.png"),
    require("./Silver/shield-silver-5.png"),
    require("./Silver/shield-silver-6.png"),
    require("./Silver/shield-silver-7.png"),
    require("./Silver/shield-silver-8.png"),
    require("./Silver/shield-silver-9.png"),
    require("./Silver/shield-silver-10.png"),
    require("./Silver/shield-silver-11.png"),
    require("./Silver/shield-silver-12.png"),
  ],
  Gold: [
    require("./Gold/shield-gold-1.png"),
    require("./Gold/shield-gold-2.png"),
    require("./Gold/shield-gold-3.png"),
    require("./Gold/shield-gold-4.png"),
    require("./Gold/shield-gold-5.png"),
    require("./Gold/shield-gold-6.png"),
    require("./Gold/shield-gold-7.png"),
    require("./Gold/shield-gold-8.png"),
    require("./Gold/shield-gold-9.png"),
    require("./Gold/shield-gold-10.png"),
    require("./Gold/shield-gold-11.png"),
    require("./Gold/shield-gold-12.png"),
  ],
  Platinum: [
    require("./Platinum/shield-platinum-1.png"),
    require("./Platinum/shield-platinum-2.png"),
    require("./Platinum/shield-platinum-3.png"),
    require("./Platinum/shield-platinum-4.png"),
    require("./Platinum/shield-platinum-5.png"),
    require("./Platinum/shield-platinum-6.png"),
    require("./Platinum/shield-platinum-7.png"),
    require("./Platinum/shield-platinum-8.png"),
    require("./Platinum/shield-platinum-9.png"),
    require("./Platinum/shield-platinum-10.png"),
    require("./Platinum/shield-platinum-11.png"),
    require("./Platinum/shield-platinum-12.png"),
  ],
  Amethyst: [
    require("./Amethyst/shield-amethyst-1.png"),
    require("./Amethyst/shield-amethyst-2.png"),
    require("./Amethyst/shield-amethyst-3.png"),
    require("./Amethyst/shield-amethyst-4.png"),
    require("./Amethyst/shield-amethyst-5.png"),
    require("./Amethyst/shield-amethyst-6.png"),
    require("./Amethyst/shield-amethyst-7.png"),
    require("./Amethyst/shield-amethyst-8.png"),
    require("./Amethyst/shield-amethyst-9.png"),
    require("./Amethyst/shield-amethyst-10.png"),
    require("./Amethyst/shield-amethyst-11.png"),
    require("./Amethyst/shield-amethyst-12.png"),
  ],
  Ruby: [
    require("./Ruby/shield-ruby-1.png"),
    require("./Ruby/shield-ruby-2.png"),
    require("./Ruby/shield-ruby-3.png"),
    require("./Ruby/shield-ruby-4.png"),
    require("./Ruby/shield-ruby-5.png"),
    require("./Ruby/shield-ruby-6.png"),
    require("./Ruby/shield-ruby-7.png"),
    require("./Ruby/shield-ruby-8.png"),
    require("./Ruby/shield-ruby-9.png"),
    require("./Ruby/shield-ruby-10.png"),
    require("./Ruby/shield-ruby-11.png"),
    require("./Ruby/shield-ruby-12.png"),
  ],
  Sapphire: [
    require("./Sapphire/shield-sapphire-1.png"),
    require("./Sapphire/shield-sapphire-2.png"),
    require("./Sapphire/shield-sapphire-3.png"),
    require("./Sapphire/shield-sapphire-4.png"),
    require("./Sapphire/shield-sapphire-5.png"),
    require("./Sapphire/shield-sapphire-6.png"),
    require("./Sapphire/shield-sapphire-7.png"),
    require("./Sapphire/shield-sapphire-8.png"),
    require("./Sapphire/shield-sapphire-9.png"),
    require("./Sapphire/shield-sapphire-10.png"),
    require("./Sapphire/shield-sapphire-11.png"),
    require("./Sapphire/shield-sapphire-12.png"),
  ],
  Onyx: [
    require("./Onyx/shield-onyx-1.png"),
    require("./Onyx/shield-onyx-2.png"),
    require("./Onyx/shield-onyx-3.png"),
    require("./Onyx/shield-onyx-4.png"),
    require("./Onyx/shield-onyx-5.png"),
    require("./Onyx/shield-onyx-6.png"),
    require("./Onyx/shield-onyx-7.png"),
    require("./Onyx/shield-onyx-8.png"),
    require("./Onyx/shield-onyx-9.png"),
    require("./Onyx/shield-onyx-10.png"),
    require("./Onyx/shield-onyx-11.png"),
    require("./Onyx/shield-onyx-12.png"),
  ],
  Master: [
    require("./Master/shield-master-1.png"),
    require("./Master/shield-master-2.png"),
    require("./Master/shield-master-3.png"),
    require("./Master/shield-master-4.png"),
    require("./Master/shield-master-5.png"),
    require("./Master/shield-master-6.png"),
    require("./Master/shield-master-7.png"),
    require("./Master/shield-master-8.png"),
    require("./Master/shield-master-9.png"),
    require("./Master/shield-master-10.png"),
    require("./Master/shield-master-11.png"),
    require("./Master/shield-master-12.png"),
  ],
};

export type RankingName = keyof typeof rankingIcons;